version: "3.3"
services:
  mongo:
    restart: always
    image: mongo
    volumes:
    - /data_storages/project
    ports: 
    - "27017:27017"
  web:
    build: ./backend/
    env_file:
      - .env
    environment:
      WAIT_HOSTS: mongo:27017
    command: ["npm","run", "docker:dev"]
    ports:
    - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo
