version: "3.3"
services:
  mongo:
    restart: always
    image: mongo
    volumes:
      - /data_storages/project
    ports:
      - "27017:27017"
  backend1:
    build: ./backend/
    tty: true
    env_file:
      - .env
    environment:
      WAIT_HOSTS: mongo:27017
    command: ["npm", "run", "docker:dev"]
    ports:
      - "3001:3000"
    depends_on:
      - mongo
    links:
      - mongo
  backend2:
    build: ./backend/
    tty: true
    env_file:
      - .env
    environment:
      WAIT_HOSTS: mongo:27017
    command: ["npm", "run", "docker:dev"]
    ports:
      - "3002:3000"
    depends_on:
      - mongo
    links:
      - mongo
  nginx:
    build: ./nginx
    tty: true
    links:
      - backend1
      - backend2
    ports:
      - 8080:8080
