version: "2"
services:
  mongo:
    restart: always
    image: mongo
    volumes:
    - /data_storages/project
    ports: 
    - "27017:27017"
  web:
    build: ./backend/
    env_file:
      - .env
    command: npm run docker:dev
    ports:
    - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo
